apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: rfreire1409-dev
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: rfreire1409-dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: app
          image: docker.io/jorftama/quansfer-backend:1.0
          ports:
            - containerPort: 8000
          env:
            - name: UPLOAD_DIR
              value: /data/uploads
          volumeMounts:
            - name: uploads
              mountPath: /data/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
