apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: rfreire1409-dev
spec:
  replicas: 1
  template:
    spec:
      affinity: null
      containers:
        - name: app
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
