apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: rfreire1409-dev
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["backend"]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: app
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
