apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  namespace: rfreire1409-dev
data:
  test.js: |
    import http from 'k6/http';
    import { sleep, check } from 'k6';

    export let options = {
      vus: __ENV.VUS ? parseInt(__ENV.VUS) : 20,
      duration: __ENV.DURATION || '2m',
      thresholds: {
        http_req_duration: ['p(95)<800'],
        checks: ['rate>0.99'],
      },
    };

    const BASE_URL = __ENV.BASE_URL || 'http://backend.rfreire1409-dev.svc.cluster.local:8000';

    export default function () {
      const res = http.get(`${BASE_URL}/`);
      check(res, {
        'status is 200': (r) => r.status === 200,
      });
      sleep(0.3);
    }
